apiVersion: batch/v1
kind: CronJob
metadata:
  name: evicted-cleaner
  namespace: k8s-admin-jobs
spec:
  schedule: "*/15 * * * *"  # Runs every 2 minutes
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: sa-cleaner
          containers:
            - name: evicted-cleaner
              image: bitnami/kubectl
              command:
                - /bin/bash
                - '-c'
                - "kubectl get pods --all-namespaces --field-selector=status.phase=Failed | grep Evicted | awk '{print $2 \" -n \" $1}' | xargs -I {} kubectl delete pod {}"
          restartPolicy: OnFailure
