apiVersion: v1
kind: ServiceAccount
metadata:
  name: sa_cleaner
  namespace: k8s-admin-jobs

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pod-eviction-deleter
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["delete"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: sa-cleaner-pod-eviction-binding
subjects:
- kind: ServiceAccount
  name: sa_cleaner
  namespace: k8s-admin-jobs
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: pod-eviction-deleter
